version: '3.8'

services:
  uapp-api:
    build: .
    image: uapp-automation-api:latest
    container_name: uapp_api_service
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./adb-keys:/root/.android
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - PYTHONUNBUFFERED=1
      - WS_SCRCPY_CONFIG=/app/config.yaml
      # 🚀 INJECTED HERE: One single source of truth for your static IP!
      - DEVICE_IP=192.168.111.48:5555